# Site settings
title: UMD Business Librarian
author: 
  name: Ian Moore
  email: imoore@d.umn.edu
description: "Quick links to business resources and tutorials."

# Build settings
remote_theme: jekyll/minima

include:
  - _pages
  
# Theme settings
header_pages:
  - _pages/tutorials.md